#!/usr/bin/python
"""Generates the README.rst based on the long_description of
the setup.py including the docstrings of the commands.

"""
import os

if __name__ == '__main__':
    root_dir = os.path.dirname(
        os.path.abspath(__file__))
    # chdir to root dir
    os.chdir(root_dir)

    # we need to be able to import those things
    from ftw.manager import ftwCommand
    from ftw.manager import commands
    from ftw.manager import config

    # get description
    from distutils.core import run_setup
    egg = run_setup('setup.py')
    description = egg.get_long_description()

    # write to README.rst
    file_ = open('README.rst', 'w')
    file_.write(description)
    file_.close()
    print 'wrote README.rst'
