import checkdocs
import checkout
import dependencytests
import develop
import help
import i18ndude
import multiinstance
import release
import selfupdate
import switch
import testcmd
import version
import zopeinstance
